Todo functions branch
App-Developer8866/Webpack_Todo_List pull request #3
Opened 2023-06-14 19:04 UTC by App-Developer8866

Following changes:

- Add function
- Remove function
-

2023-06-14 19:29 UTC, Shedrack-Sunday requested changes
Hello  @App-Developer8866 👋 

# CHANGES REQUIRED ♻️

Great work on the project 👏
You've done extremely well so far in this project,  However, there are some adjustments you need to make to move to the next project. 💯

![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)

## Highlights   
- Good use of GitHub features ✔️  
- Kudus on the use of modules✔️ 
  
# Required Changes  🌵 

- [ ] You made some impressive implementations which I must say is a job well done. However, there are a few  I suggest   you make In line with the requirement

_Check the comments for a detailed review 

# Optional suggestions 

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing really improves your application.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-06-14 19:29 UTC, Shedrack-Sunday commented on modules/addToList.js
> +  toDoList.push({ value, completed, index });
- [ ] ES6 improves JavaScript by introducing new features such as arrow functions, template literals, and classes, which enhance code readability and maintainability. It also provides modules for better organization and code reusability in larger projects, promoting collaboration among developers.
- Kindly refactor your code to use `ES6` 👍

2023-06-14 19:29 UTC, Shedrack-Sunday commented on modules/clearList.js
> +export default function clearList(taskList) {
- [ ] Kindly check my comment on the use of `es6` on the addToList file which is very detailed 👍

2023-06-14 19:29 UTC, Shedrack-Sunday commented on modules/displayLists.js
> +export default function displayLists(taskList) {
- [ ]  Kindly check my comment on the use of es6 on the addToList file which is very detailed 👍

2023-06-14 19:29 UTC, Shedrack-Sunday commented on modules/editList.js
> +export default function editList(index, value, toDoList) {
- [ ]  Kindly check my comment on the use of es6 on the addToList file which is very detailed 👍

2023-06-14 19:29 UTC, Shedrack-Sunday commented on modules/markComplete.js
> +  const checkbox = event.target;
- [ ]  Kindly check my comment on the use of es6 on the addToList file which is very detailed 👍

2023-06-14 19:29 UTC, Shedrack-Sunday commented on modules/markUnComplete.js
> +  const checkbox = event.target;
-  [ ]  Kindly check my comment on the use of es6 on the addToList file which is very detailed 👍

2023-06-14 19:29 UTC, Shedrack-Sunday commented on modules/refreshList.js
> +export default function refreshList(toDoList) {
- [ ]  Kindly check my comment on the use of es6 on the addToList file which is very detailed 👍

2023-06-14 19:29 UTC, Shedrack-Sunday commented on modules/removeListitem.js
> +export default function removeListitem(index, toDoList) {
- [ ]  Kindly check my comment on the use of es6 on the addToList file which is very detailed 👍

2023-06-14 19:29 UTC, Shedrack-Sunday commented on modules/updateBookData.js
> +  const tasksList = JSON.parse(localStorage.getItem('tasksList'));
- [ ]  Kindly check my comment on the use of es6 on the addToList file which is very detailed 👍

2023-06-14 19:29 UTC, Shedrack-Sunday commented on modules/updateLists.js
> +  displayLists(toDoList);
- [ ]  Kindly check my comment on the use of es6 on the addToList file which is very detailed 👍

2023-06-14 19:29 UTC, Shedrack-Sunday commented on modules/updateLists.js
> +    const listItem = event.target.closest('li');
- [ ]  Kindly check my comment on the use of es6 on the addToList file which is very detailed 👍

2023-06-14 19:29 UTC, Shedrack-Sunday commented on modules/updateStatus.js
> +export default function updateStatus(index, status, toDoList) {
- [ ]  Kindly check my comment on the use of es6 on the addToList file which is very detailed 👍

2023-06-14 20:12 UTC, DuaneDave requested changes
Hi @App-Developer8866 👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
✔️ The way your code is modularized is quite intuitive and great

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-14 20:12 UTC, DuaneDave commented on modules/markUnComplete.js
> +  const checkbox = event.target;
As previously mentioned and as part of the project requirements, consider refactoring this function to use es6 arrow function syntax for readability and to satisfy the milestone requirements

2023-06-14 20:12 UTC, DuaneDave commented on modules/refreshList.js
> +export default function refreshList(toDoList) {
As previously mentioned, and as part of the project requirements, consider refactoring this function to use es6 arrow function syntax for readability and to satisfy the milestone requirements.

2023-06-15 08:19 UTC, jerryowusu approved these changes
Hi @App-Developer8866 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![CookedDelectableDolphin-size_restricted](https://github.com/App-Developer8866/Webpack_Todo_List/assets/65233860/45b6eabe-91fb-46b8-b247-b83dd815e8c9)


## Highlights
Used modules :+1: 
Used arrow functions :+1: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-15 09:02 UTC, merged